# Generated by Django 4.1.7 on 2023-05-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_subs_subj_lessons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subj',
            new_name='Subject11',
        ),
    ]
