# Generated by Django 4.1.7 on 2023-05-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_subj_subject11'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='main.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject11',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='person',
        ),
    ]
