# Generated by Django 4.2 on 2023-05-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_first_name_person_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='name2',
        ),
    ]
