# Generated by Django 4.1.7 on 2023-05-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subs',
            new_name='Subj',
        ),
    ]
