# Generated by Django 4.1.7 on 2023-05-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_subs_subj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subj',
            old_name='subs',
            new_name='lessons',
        ),
    ]
