# Generated by Django 4.1.7 on 2023-05-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sub_subject_person_delete_subj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='first_name',
        ),
    ]
