# Generated by Django 4.1.7 on 2023-05-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_name_person_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='first_name',
            new_name='name',
        ),
    ]
