# Generated by Django 4.2 on 2023-05-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_subject_person_delete_person_delete_subject'),
        ('main', '0010_rename_name_subject_name2'),
    ]

    operations = [
    ]
