# Generated by Django 4.2 on 2023-05-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_person_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name2',
            new_name='name',
        ),
    ]
