# Generated by Django 4.2 on 2023-05-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_name2_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='name2',
        ),
    ]
